id: AB78BC882
title: Prayer for the Long Life of Soktsé Rinpoche
type: translation
pechas:
- I99D8F46D
- I58541A51
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:48:21.492669
  last_modified_at: 2023-01-04 11:48:21.492673
  collections:
  - Dudjom Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I99D8F46D/4591: BF45
  I58541A51/C0D5: BF45
